name: "osnet_reid"
backend: "onnxruntime"
max_batch_size: 16

input [
    {
        name: "input"
        data_type: TYPE_FP32
        dims: [3, 256, 128]
    }
]

output [
    {
        name: "output"
        data_type: TYPE_FP32
        dims: [512] 
    }
]

dynamic_batching {
    max_queue_delay_microseconds: 5000
    preferred_batch_size: [4, 6, 16]
}