services:
  triton-server:
    image: nvcr.io/nvidia/tritonserver:24.01-py3
    ports:
      - "8000:8000" # http
      - "8001:8001" # grpc
      - "8002:8002" # metrics
    volumes:
      - ./triton_model_repo:/models
    command: [ "tritonserver", "--model-repository=/models" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    shm_size: '2gb'
